[package]
name = "cryonet"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
dyn-clone = "1.0.20"
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
typetag = "0.2.21"
